version: "3.9"

services:
  api:
    build:
      context: .
      target: fastapi-api
    container_name: fastapi-app
    restart: always
    env_file:
      - .env
    ports:
      - "${APP_PORT}:80"
    network_mode: bridge
    extra_hosts:
      - "host.docker.internal:host-gateway"
